server:
  port: 8081

spring:
  ### 데이터베이스 ###
  datasource:
    driver-class-name: org.postgresql.Driver
    username: skcc
    password: skcc
    url: jdbc:postgresql://58.227.126.30:15432/skcc
  #    url: jdbc:h2:tcp://localhost/~/test

  ### 파일  ###
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB # 전체 요청(파일 + 데이터)의 최대 크기

  ### JPA 설정 ###
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        show_sql: true

### JWT 설정 ###
jwt:
  secret: skcc-secret-key-skcc-secret-key-skcc-secret-key-skcc-secret-key # 최소 64바이트 이상
  expiration: 1800000 # 30분

### MyBatis ###
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 테이블 컬럼 명이랑 DTO 필드명이랑 다를경우

### 로깅 설정
logging:
  level:
    root: info # 전체 로그 레벨
    springframework:
      boot:
        autoconfigure: debug

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)]%X{traceId}%X{depth} %msg%n" # 콘솔 로그 패턴
# 로그 파일 관리
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)]%X{traceId}%X{depth} %msg%n" # 콘솔 로그 패턴
#  file:
#    name: logs/app.log # 파일 로그 경로 지정
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
#      max-file-size: 10MB

# Swagger UI 설정
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
