server:
  port: 8080

spring:
  ### 데이터베이스 ###
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb;
  #    url: jdbc:h2:tcp://localhost/~/test
  h2:
    console:
      enabled: true
      path: /h2-console

  ### 파일  ###
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 105MB # 전체 요청(파일 + 데이터)의 최대 크기

  ### JPA 설정 ###
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true

### MyBatis ###
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 테이블 컬럼 명이랑 DTO 필드명이랑 다를경우

### 로깅 설정
logging:
  level:
    root: info # 전체 로그 레벨
    springframework:
      boot:
        autoconfigure: debug

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)]%X{traceId}%X{depth} %msg%n" # 콘솔 로그 패턴
# 로그 파일 관리
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread][%highlight(%-5level)]%X{traceId}%X{depth} %msg%n" # 콘솔 로그 패턴
#  file:
#    name: logs/app.log # 파일 로그 경로 지정
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
#      max-file-size: 10MB

# Swagger UI 설정
springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
