import type { ApplicantSearchResult, ApplicantDetail, CodeGroup, CodeDetail } from "@/types/common"

// 수험생 검색 결과 목업 데이터
export const mockApplicantSearchResults: ApplicantSearchResult[] = [
  {
    applicantId: "A2023001",
    name: "김지원",
    birthDate: "2005-03-15",
    examNumber: "2024S1001",
  },
  {
    applicantId: "A2023002",
    name: "이수민",
    birthDate: "2005-05-22",
    examNumber: "2024S1002",
  },
  {
    applicantId: "A2023003",
    name: "박준호",
    birthDate: "2005-08-10",
    examNumber: "2024S1003",
  },
  {
    applicantId: "A2023004",
    name: "최유진",
    birthDate: "2005-11-27",
    examNumber: "2024S1004",
  },
  {
    applicantId: "A2023005",
    name: "정민수",
    birthDate: "2005-01-05",
    examNumber: "2024S1005",
  },
  {
    applicantId: "A2023006",
    name: "강서연",
    birthDate: "2005-07-18",
    examNumber: "2024S1006",
  },
  {
    applicantId: "A2023007",
    name: "윤도현",
    birthDate: "2005-09-30",
    examNumber: "2024S1007",
  },
  {
    applicantId: "A2023008",
    name: "한지민",
    birthDate: "2005-04-12",
    examNumber: "2024S1008",
  },
  {
    applicantId: "A2023009",
    name: "송태양",
    birthDate: "2005-02-28",
    examNumber: "2024S1009",
  },
  {
    applicantId: "A2023010",
    name: "임하늘",
    birthDate: "2005-12-01",
    examNumber: "2024S1010",
  },
]

// 수험생 상세 정보 목업 데이터
export const mockApplicantDetails: Record<string, ApplicantDetail> = {
  A2023001: {
    basicInfo: {
      applicantId: "A2023001",
      name: "김지원",
      birthDate: "2005-03-15",
      gender: "여",
      phoneNumber: "010-1234-5678",
      email: "jiwon.kim@example.com",
      address: "서울특별시 강남구 테헤란로 123",
      createdAt: "2023-08-15T10:30:00Z",
      uniqueId: "050315-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1001,
        round: "2024학년도 수시",
        type: "학생부종합",
        dept: "컴퓨터공학과",
        status: "접수완료",
        examNumber: "2024S1001",
        score: 87.5,
        rank: 15,
      },
      {
        applicationId: 1002,
        round: "2024학년도 수시",
        type: "학생부교과",
        dept: "전자공학과",
        status: "접수완료",
        examNumber: "2024S1001E",
        score: 92.3,
        rank: 8,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.5,
      majorSuitability: 4.2,
      personality: 4.8,
      potentialForGrowth: 4.3,
      overallRating: 4.5,
      comments: "학업 역량과 인성이 우수하며, 전공 적합성도 높음. 발전 가능성이 큰 학생으로 평가됨.",
    },
    recruitmentLogs: [
      {
        logId: 101,
        applicationId: 1001,
        recruitmentRound: 1,
        callStartedAt: "2023-12-15T14:30:00Z",
        callEndedAt: "2023-12-15T14:40:00Z",
        result: "합격",
        memo: "합격 통보 완료, 등록 의사 확인",
        recordingFilePath: "/recordings/A2023001_20231215.mp3",
        counselorId: "counselor1",
      },
    ],
    counselingLogs: [
      {
        counselingLogId: 201,
        applicantName: "김지원",
        applicantContact: "010-1234-5678",
        applicantScores: "내신 1.5등급, 수능 모의고사 국어 90점, 수학 85점, 영어 1등급",
        counselingContent: "컴퓨터공학과와 전자공학과 지원 상담. 학생부종합전형과 학생부교과전형 지원 전략 안내.",
        counselorId: "counselor1",
        counseledAt: "2023-07-10T13:00:00Z",
      },
      {
        counselingLogId: 202,
        applicantName: "김지원",
        applicantContact: "010-1234-5678",
        applicantScores: "내신 1.5등급, 수능 모의고사 국어 92점, 수학 88점, 영어 1등급",
        counselingContent: "자기소개서 작성 방향 상담. 교내 활동 중심으로 작성 권장.",
        counselorId: "counselor2",
        counseledAt: "2023-08-05T15:30:00Z",
      },
    ],
  },
  A2023002: {
    basicInfo: {
      applicantId: "A2023002",
      name: "이수민",
      birthDate: "2005-05-22",
      gender: "남",
      phoneNumber: "010-2345-6789",
      email: "sumin.lee@example.com",
      address: "서울특별시 서초구 서초대로 456",
      createdAt: "2023-08-16T11:45:00Z",
      uniqueId: "050522-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1003,
        round: "2024학년도 수시",
        type: "학생부종합",
        dept: "경영학과",
        status: "접수완료",
        examNumber: "2024S1002",
        score: 85.8,
        rank: 20,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.2,
      majorSuitability: 4.5,
      personality: 4.3,
      potentialForGrowth: 4.4,
      overallRating: 4.3,
      comments: "경영학 분야에 대한 관심과 적성이 뚜렷함. 리더십과 의사소통 능력이 우수함.",
    },
    recruitmentLogs: [],
    counselingLogs: [
      {
        counselingLogId: 203,
        applicantName: "이수민",
        applicantContact: "010-2345-6789",
        applicantScores: "내신 2.1등급, 수능 모의고사 국어 85점, 수학 80점, 영어 2등급",
        counselingContent: "경영학과 지원 상담. 학생부종합전형 지원 전략 안내.",
        counselorId: "counselor1",
        counseledAt: "2023-07-12T10:30:00Z",
      },
    ],
  },
  A2023003: {
    basicInfo: {
      applicantId: "A2023003",
      name: "박준호",
      birthDate: "2005-08-10",
      gender: "남",
      phoneNumber: "010-3456-7890",
      email: "junho.park@example.com",
      address: "서울특별시 송파구 올림픽로 789",
      createdAt: "2023-08-17T09:15:00Z",
      uniqueId: "050810-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1004,
        round: "2024학년도 수시",
        type: "학생부교과",
        dept: "컴퓨터공학과",
        status: "접수완료",
        examNumber: "2024S1003",
        score: 94.2,
        rank: 5,
      },
      {
        applicationId: 1005,
        round: "2024학년도 수시",
        type: "논술",
        dept: "전자공학과",
        status: "접수완료",
        examNumber: "2024S1003N",
        score: 88.7,
        rank: 12,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.8,
      majorSuitability: 4.6,
      personality: 4.2,
      potentialForGrowth: 4.5,
      overallRating: 4.6,
      comments:
        "학업 성취도가 매우 높으며, 특히 수학과 과학 분야에서 우수한 능력을 보임. 컴퓨터 프로그래밍 경험이 풍부함.",
    },
    recruitmentLogs: [],
    counselingLogs: [
      {
        counselingLogId: 204,
        applicantName: "박준호",
        applicantContact: "010-3456-7890",
        applicantScores: "내신 1.2등급, 수능 모의고사 국어 88점, 수학 95점, 영어 1등급",
        counselingContent: "컴퓨터공학과와 전자공학과 지원 상담. 학생부교과전형과 논술전형 지원 전략 안내.",
        counselorId: "counselor2",
        counseledAt: "2023-07-15T14:00:00Z",
      },
    ],
  },
  A2023004: {
    basicInfo: {
      applicantId: "A2023004",
      name: "최유진",
      birthDate: "2005-11-27",
      gender: "여",
      phoneNumber: "010-4567-8901",
      email: "yujin.choi@example.com",
      address: "서울특별시 마포구 홍대로 101",
      createdAt: "2023-08-18T13:20:00Z",
      uniqueId: "051127-2345678",
    },
    applicationHistory: [
      {
        applicationId: 1006,
        round: "2024학년도 수시",
        type: "학생부종합",
        dept: "심리학과",
        status: "접수완료",
        examNumber: "2024S1004",
        score: 89.5,
        rank: 10,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.3,
      majorSuitability: 4.7,
      personality: 4.6,
      potentialForGrowth: 4.4,
      overallRating: 4.5,
      comments: "인문사회 분야에 대한 깊은 이해와 관심을 보임. 심리학 관련 활동이 풍부하며, 분석적 사고력이 우수함.",
    },
    recruitmentLogs: [],
    counselingLogs: [
      {
        counselingLogId: 205,
        applicantName: "최유진",
        applicantContact: "010-4567-8901",
        applicantScores: "내신 1.8등급, 수능 모의고사 국어 92점, 수학 82점, 영어 1등급",
        counselingContent: "심리학과 지원 상담. 학생부종합전형 지원 전략 안내.",
        counselorId: "counselor1",
        counseledAt: "2023-07-18T11:00:00Z",
      },
    ],
  },
  A2023005: {
    basicInfo: {
      applicantId: "A2023005",
      name: "정민수",
      birthDate: "2005-01-05",
      gender: "남",
      phoneNumber: "010-5678-9012",
      email: "minsu.jung@example.com",
      address: "서울특별시 영등포구 여의도로 202",
      createdAt: "2023-08-19T10:10:00Z",
      uniqueId: "050105-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1007,
        round: "2024학년도 수시",
        type: "학생부교과",
        dept: "경영학과",
        status: "접수완료",
        examNumber: "2024S1005",
        score: 91.8,
        rank: 7,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.5,
      majorSuitability: 4.4,
      personality: 4.3,
      potentialForGrowth: 4.2,
      overallRating: 4.4,
      comments: "경제, 경영 분야에 대한 관심이 높으며, 수리적 능력이 우수함. 리더십 활동 경험이 풍부함.",
    },
    recruitmentLogs: [],
    counselingLogs: [],
  },
  A2023006: {
    basicInfo: {
      applicantId: "A2023006",
      name: "강서연",
      birthDate: "2005-07-18",
      gender: "여",
      phoneNumber: "010-6789-0123",
      email: "seoyeon.kang@example.com",
      address: "서울특별시 강동구 천호대로 303",
      createdAt: "2023-08-20T14:25:00Z",
      uniqueId: "050718-2345678",
    },
    applicationHistory: [
      {
        applicationId: 1008,
        round: "2024학년도 수시",
        type: "학생부종합",
        dept: "의예과",
        status: "접수완료",
        examNumber: "2024S1006",
        score: 96.5,
        rank: 3,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.9,
      majorSuitability: 4.8,
      personality: 4.7,
      potentialForGrowth: 4.8,
      overallRating: 4.8,
      comments:
        "학업 성취도가 매우 탁월하며, 의학 분야에 대한 관심과 이해도가 높음. 봉사활동 경험이 풍부하고 인성이 우수함.",
    },
    recruitmentLogs: [],
    counselingLogs: [
      {
        counselingLogId: 206,
        applicantName: "강서연",
        applicantContact: "010-6789-0123",
        applicantScores: "내신 1.0등급, 수능 모의고사 국어 95점, 수학 98점, 영어 1등급",
        counselingContent: "의예과 지원 상담. 학생부종합전형 지원 전략 안내.",
        counselorId: "counselor2",
        counseledAt: "2023-07-20T15:30:00Z",
      },
    ],
  },
  A2023007: {
    basicInfo: {
      applicantId: "A2023007",
      name: "윤도현",
      birthDate: "2005-09-30",
      gender: "남",
      phoneNumber: "010-7890-1234",
      email: "dohyun.yoon@example.com",
      address: "서울특별시 노원구 노원로 404",
      createdAt: "2023-08-21T09:50:00Z",
      uniqueId: "050930-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1009,
        round: "2024학년도 수시",
        type: "논술",
        dept: "컴퓨터공학과",
        status: "접수완료",
        examNumber: "2024S1007",
        score: 85.2,
        rank: 18,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.2,
      majorSuitability: 4.5,
      personality: 4.1,
      potentialForGrowth: 4.3,
      overallRating: 4.3,
      comments: "논리적 사고력과 문제 해결 능력이 우수함. 컴퓨터 프로그래밍에 대한 관심과 경험이 있음.",
    },
    recruitmentLogs: [],
    counselingLogs: [],
  },
  A2023008: {
    basicInfo: {
      applicantId: "A2023008",
      name: "한지민",
      birthDate: "2005-04-12",
      gender: "여",
      phoneNumber: "010-8901-2345",
      email: "jimin.han@example.com",
      address: "서울특별시 강서구 공항대로 505",
      createdAt: "2023-08-22T11:35:00Z",
      uniqueId: "050412-2345678",
    },
    applicationHistory: [
      {
        applicationId: 1010,
        round: "2024학년도 수시",
        type: "학생부교과",
        dept: "심리학과",
        status: "접수완료",
        examNumber: "2024S1008",
        score: 90.7,
        rank: 9,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.4,
      majorSuitability: 4.6,
      personality: 4.5,
      potentialForGrowth: 4.3,
      overallRating: 4.5,
      comments: "인문학적 소양이 풍부하며, 심리학에 대한 관심과 이해도가 높음. 공감 능력과 의사소통 능력이 우수함.",
    },
    recruitmentLogs: [],
    counselingLogs: [],
  },
  A2023009: {
    basicInfo: {
      applicantId: "A2023009",
      name: "송태양",
      birthDate: "2005-02-28",
      gender: "남",
      phoneNumber: "010-9012-3456",
      email: "taeyang.song@example.com",
      address: "서울특별시 동작구 동작대로 606",
      createdAt: "2023-08-23T13:40:00Z",
      uniqueId: "050228-1234567",
    },
    applicationHistory: [
      {
        applicationId: 1011,
        round: "2024학년도 수시",
        type: "학생부종합",
        dept: "전자공학과",
        status: "접수완료",
        examNumber: "2024S1009",
        score: 88.3,
        rank: 14,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.3,
      majorSuitability: 4.5,
      personality: 4.2,
      potentialForGrowth: 4.4,
      overallRating: 4.4,
      comments: "과학 분야에 대한 관심과 이해도가 높으며, 특히 전자공학 관련 활동 경험이 풍부함.",
    },
    recruitmentLogs: [],
    counselingLogs: [],
  },
  A2023010: {
    basicInfo: {
      applicantId: "A2023010",
      name: "임하늘",
      birthDate: "2005-12-01",
      gender: "여",
      phoneNumber: "010-0123-4567",
      email: "haneul.lim@example.com",
      address: "서울특별시 성북구 성북로 707",
      createdAt: "2023-08-24T10:15:00Z",
      uniqueId: "051201-2345678",
    },
    applicationHistory: [
      {
        applicationId: 1012,
        round: "2024학년도 수시",
        type: "학생부교과",
        dept: "경영학과",
        status: "접수완료",
        examNumber: "2024S1010",
        score: 93.1,
        rank: 6,
      },
    ],
    evaluationSummary: {
      academicAbility: 4.6,
      majorSuitability: 4.4,
      personality: 4.5,
      potentialForGrowth: 4.3,
      overallRating: 4.5,
      comments: "경제, 경영 분야에 대한 관심이 높으며, 분석적 사고력과 리더십이 우수함.",
    },
    recruitmentLogs: [],
    counselingLogs: [],
  },
}

// 공통 코드 그룹 목업 데이터
export const mockCodeGroups: CodeGroup[] = [
  {
    groupCode: "ADMISSION_ROUND",
    groupName: "모집 시기",
    description: "입학 전형 모집 시기 구분",
    isActive: true,
  },
  {
    groupCode: "ADMISSION_TYPE",
    groupName: "전형 유형",
    description: "입학 전형 유형 구분",
    isActive: true,
  },
  {
    groupCode: "DEPARTMENT",
    groupName: "모집 단위",
    description: "대학 내 모집 단위(학과) 구분",
    isActive: true,
  },
  {
    groupCode: "APPLICATION_STATUS",
    groupName: "원서 상태",
    description: "원서 접수 상태 구분",
    isActive: true,
  },
  {
    groupCode: "EVALUATION_ITEM",
    groupName: "평가 항목",
    description: "학생부종합전형 평가 항목",
    isActive: true,
  },
  {
    groupCode: "COUNSELING_TYPE",
    groupName: "상담 유형",
    description: "입학 상담 유형 구분",
    isActive: true,
  },
  {
    groupCode: "PAYMENT_METHOD",
    groupName: "결제 방법",
    description: "전형료/등록금 결제 방법",
    isActive: true,
  },
  {
    groupCode: "REFUND_REASON",
    groupName: "환불 사유",
    description: "등록금 환불 사유",
    isActive: true,
  },
  {
    groupCode: "USER_ROLE",
    groupName: "사용자 역할",
    description: "시스템 사용자 역할 구분",
    isActive: true,
  },
  {
    groupCode: "BOARD_TYPE",
    groupName: "게시판 유형",
    description: "게시판 유형 구분",
    isActive: true,
  },
]

// 공통 코드 상세 목업 데이터
export const mockCodeDetails: Record<string, CodeDetail[]> = {
  ADMISSION_ROUND: [
    {
      groupCode: "ADMISSION_ROUND",
      code: "2024_EARLY",
      codeName: "2024학년도 수시",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_ROUND",
      code: "2024_REGULAR",
      codeName: "2024학년도 정시",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_ROUND",
      code: "2023_EARLY",
      codeName: "2023학년도 수시",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_ROUND",
      code: "2023_REGULAR",
      codeName: "2023학년도 정시",
      sortOrder: 4,
      isActive: true,
    },
  ],
  ADMISSION_TYPE: [
    {
      groupCode: "ADMISSION_TYPE",
      code: "COMPREHENSIVE",
      codeName: "학생부종합",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_TYPE",
      code: "SUBJECT_GRADE",
      codeName: "학생부교과",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_TYPE",
      code: "ESSAY",
      codeName: "논술",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_TYPE",
      code: "CSAT",
      codeName: "수능위주",
      sortOrder: 4,
      isActive: true,
    },
    {
      groupCode: "ADMISSION_TYPE",
      code: "PRACTICAL",
      codeName: "실기/실적",
      sortOrder: 5,
      isActive: true,
    },
  ],
  DEPARTMENT: [
    {
      groupCode: "DEPARTMENT",
      code: "CS",
      codeName: "컴퓨터공학과",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "DEPARTMENT",
      code: "EE",
      codeName: "전자공학과",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "DEPARTMENT",
      code: "BIZ",
      codeName: "경영학과",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "DEPARTMENT",
      code: "MED",
      codeName: "의예과",
      sortOrder: 4,
      isActive: true,
    },
    {
      groupCode: "DEPARTMENT",
      code: "PSYCH",
      codeName: "심리학과",
      sortOrder: 5,
      isActive: true,
    },
  ],
  APPLICATION_STATUS: [
    {
      groupCode: "APPLICATION_STATUS",
      code: "RECEIVED",
      codeName: "접수완료",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "APPLICATION_STATUS",
      code: "EVALUATING",
      codeName: "평가중",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "APPLICATION_STATUS",
      code: "ACCEPTED",
      codeName: "합격",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "APPLICATION_STATUS",
      code: "REJECTED",
      codeName: "불합격",
      sortOrder: 4,
      isActive: true,
    },
    {
      groupCode: "APPLICATION_STATUS",
      code: "REGISTERED",
      codeName: "등록완료",
      sortOrder: 5,
      isActive: true,
    },
    {
      groupCode: "APPLICATION_STATUS",
      code: "REFUNDED",
      codeName: "환불완료",
      sortOrder: 6,
      isActive: true,
    },
  ],
  EVALUATION_ITEM: [
    {
      groupCode: "EVALUATION_ITEM",
      code: "ACADEMIC",
      codeName: "학업역량",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "EVALUATION_ITEM",
      code: "MAJOR_FIT",
      codeName: "전공적합성",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "EVALUATION_ITEM",
      code: "PERSONALITY",
      codeName: "인성",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "EVALUATION_ITEM",
      code: "POTENTIAL",
      codeName: "발전가능성",
      sortOrder: 4,
      isActive: true,
    },
  ],
  COUNSELING_TYPE: [
    {
      groupCode: "COUNSELING_TYPE",
      code: "ONLINE",
      codeName: "온라인 상담",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "COUNSELING_TYPE",
      code: "PHONE",
      codeName: "전화 상담",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "COUNSELING_TYPE",
      code: "VISIT",
      codeName: "방문 상담",
      sortOrder: 3,
      isActive: true,
    },
  ],
  PAYMENT_METHOD: [
    {
      groupCode: "PAYMENT_METHOD",
      code: "CARD",
      codeName: "신용카드",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "PAYMENT_METHOD",
      code: "BANK",
      codeName: "계좌이체",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "PAYMENT_METHOD",
      code: "VIRTUAL",
      codeName: "가상계좌",
      sortOrder: 3,
      isActive: true,
    },
  ],
  REFUND_REASON: [
    {
      groupCode: "REFUND_REASON",
      code: "DOUBLE_PAYMENT",
      codeName: "이중등록",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "REFUND_REASON",
      code: "ADMISSION_CANCEL",
      codeName: "합격포기",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "REFUND_REASON",
      code: "MILITARY",
      codeName: "군입대",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "REFUND_REASON",
      code: "PERSONAL",
      codeName: "개인사유",
      sortOrder: 4,
      isActive: true,
    },
  ],
  USER_ROLE: [
    {
      groupCode: "USER_ROLE",
      code: "APPLICANT",
      codeName: "수험생",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "USER_ROLE",
      code: "ADMISSION_OFFICER",
      codeName: "입학처 담당자",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "USER_ROLE",
      code: "EVALUATOR",
      codeName: "평가위원",
      sortOrder: 3,
      isActive: true,
    },
    {
      groupCode: "USER_ROLE",
      code: "COUNSELOR",
      codeName: "상담사",
      sortOrder: 4,
      isActive: true,
    },
    {
      groupCode: "USER_ROLE",
      code: "FINANCE_OFFICER",
      codeName: "재무 담당자",
      sortOrder: 5,
      isActive: true,
    },
    {
      groupCode: "USER_ROLE",
      code: "SYSTEM_ADMIN",
      codeName: "시스템 관리자",
      sortOrder: 6,
      isActive: true,
    },
  ],
  BOARD_TYPE: [
    {
      groupCode: "BOARD_TYPE",
      code: "NOTICE",
      codeName: "공지사항",
      sortOrder: 1,
      isActive: true,
    },
    {
      groupCode: "BOARD_TYPE",
      code: "QNA",
      codeName: "Q&A",
      sortOrder: 2,
      isActive: true,
    },
    {
      groupCode: "BOARD_TYPE",
      code: "FAQ",
      codeName: "FAQ",
      sortOrder: 3,
      isActive: true,
    },
  ],
}
